fix(CleanDIFT): timestep tensor connversion from `float32` to `bfloat32` when passed to UNet
This version failed because of lack of memory ressources on Google
Colab. The process allocated more memory than was available and resulted
in the following error:

"
OutOfMemoryError: CUDA out of memory. Tried to allocate 6.00 GiB. GPU 0
has a total capacity of 14.74 GiB of which 3.58 GiB is free. Process
12076 has 11.16 GiB memory in use. Of the allocated memory 10.59 GiB is
allocated by PyTorch, and 453.57 MiB is reserved by PyTorch but
unallocated. If reserved but unallocated memory is large try setting
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.
See documentation for Memory Management
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
"

Signed-off-by: Neil Taison Rigaud <ntsrigaud14@gmail.com>